version: '3'

services:
  web:
    build:
      context: .
      args:
        - PHP_VERSION=${PHP_VERSION}
        - MAGENTO_VERSION=${MAGENTO_VERSION}
    container_name: magento2-hyva-container
    networks:
      backend:
        aliases:
          - magento2.test.com
    extra_hosts:
      - "magento2.test.com:127.0.0.1"
    environment:
      DB_SERVER: mariadb
      ELASTICSEARCH_SERVER: elasticsearch
      MAGENTO_HOST: magento2.test.com
      VIRTUAL_HOST: magento2.test.com
      COMPOSER_MEMORY_LIMIT: -1
      DONATION_ACCOUNT:
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "Adyen123@"
      ADYEN_MERCHANT:
      ADYEN_API_KEY:
      ADYEN_CLIENT_KEY:
      PHP_VERSION:
      MAGENTO_VERSION:
      DEPLOY_SAMPLEDATA: 1
      SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
      BRANCH_NAME: ${BRANCH_NAME}
    depends_on:
      - db
      - elastic
    volumes:
      - ../:/data/extensions/workdir
      - ./Makefile:/var/www/html/Makefile
      - composer:/usr/local/bin
      - magento:/var/www/html
  db:
    image: mariadb:10.11
    container_name: mariadb
    networks:
      - backend
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: magento
      MARIADB_USER: magento
      MARIADB_PASSWORD: magento
  elastic:
    image: elasticsearch:7.17.13
    container_name: elasticsearch
    networks:
      - backend
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
networks:
  backend:
volumes:
  magento:
  composer:
