<?php

/** @var Template $block */
/** @var Escaper $escaper */
/** @var HyvaCsp $hyvaCsp */

use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

?>

<script>
    function adyenDefaultComponent() {
        return {
            init() {
                console.log(window.loadedAdyenDefaultInitially)
                // the event listener is created too late so that the first click is not listened
                // so I need to handle only the first click in a specific manner
                if (!window.loadedAdyenDefaultInitially) {
                    window.loadedAdyenDefaultInitially = true;
                    this.initDefaultAdyen(this.$root.dataset.methodCode);
                }

                window.addEventListener('checkout:payment:method-list-boot', async (event) => {
                    unmountAdyenComponent();
                    await this.initDefaultAdyen(event.detail.method);
                });

                window.addEventListener('checkout:payment:method-activate', async (event) => {
                    await this.initDefaultAdyen(event.detail.method);
                });
            },
            async initDefaultAdyen(methodCode) {
                try {
                    let wire = Magewire.find('checkout.payment.methods.' + methodCode);

                    wire.refreshProperties()
                        .then(() => {
                            let methodHandler = new componentHandler(
                                methodCode,
                                wire,
                                this.$root.dataset.containerName + 'ActionContainer'
                            );

                            window.AdyenPaymentHandler = methodHandler;

                            if (methodCode !== this.$root.dataset.methodCode) {
                                methodHandler.renderMethodUnavailableMessage();
                                return;
                            }

                            if (wire.get('requiresShipping')) {
                                methodHandler.renderMessage("<?= $escaper->escapeJs(__('Please select shipping method.')) ?>");
                            } else {
                                let rawResponse = wire.get('paymentResponse');
                                let paymentMethods = JSON.parse(rawResponse);
                                methodHandler.activatePaymentMethod(
                                    methodCode,
                                    paymentMethods,
                                    this.$root.dataset.containerName + 'ActionContainer'
                                );
                                showPrimaryButton();
                            }
                        }).catch(() => {
                        console.log(`Error occurred during ${methodCode} component load`)
                    });
                } catch (e) {
                }
            }
        };
    }

    window.addEventListener('alpine:init', () => {
        Alpine.data('adyenDefaultComponent', adyenDefaultComponent);
    }, { once: true });

    window.addEventListener('checkout:init:evaluation', event => {
        hyvaCheckout.evaluation.registerValidator('validate-adyen-component-state', (element, component) => {
            let isValid;

            if (!window.AdyenPaymentHandler.actionComponent.isValid) {
                window.AdyenPaymentHandler.actionComponent.showValidation();
                isValid = false;
            } else {
                isValid = true;
            }

            return isValid;
        })
    })
</script>
<?php $hyvaCsp->registerInlineScript() ?>