<?php

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var ViewModel $viewModel */
/** @var PaymentMethodInterface $method */
/** @var Magewire $magewire */
/** @var Escaper $escaper */
/** @var MethodMetaDataInterface $methodMetaData */

use Hyva\Checkout\Model\MethodMetaDataInterface;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Checkout\ViewModel\Checkout\Payment\MethodList as ViewModel;
use Hyva\Checkout\Magewire\Checkout\Payment\MethodList as Magewire;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Quote\Api\Data\PaymentMethodInterface;

$viewModel = $viewModels->require(ViewModel::class);
$methods = $viewModel->getList();
?>
<div id="payment-methods">
    <?php if ($methods): ?>
        <ol id="payment-method-list"
            class="space-y-4"

            x-data="adyenPaymentMethodRegisterEvent"
            data-method="<?= $escaper->escapeHtmlAttr($magewire->method) ?>"
        >
            <?= $block->getChildHtml('adyen_vault_stored_cards');?>
            <?php foreach ($methods as $method): ?>
                <?php $methodCodeAttr = $method->getCode() ?>
                <?php $methodMetaData = $viewModel->getMethodMetaData($block, $method) ?>

                <li id="payment-method-option-<?= $escaper->escapeHtmlAttr($methodCodeAttr) ?>"
                    wire:key="<?= $escaper->escapeHtmlAttr($methodCodeAttr) ?>"
                >
                    <div class="flex gap-x-4">
                        <div class="flex items-center">
                            <input type="radio"
                                   class="flex-none disabled:opacity-25"
                                   id="payment-method-<?= $escaper->escapeHtmlAttr($methodCodeAttr) ?>"
                                   name="payment-method-option"
                                   value="<?= $escaper->escapeHtmlAttr($methodCodeAttr) ?>"
                                   wire:model="method"
                            />
                        </div>

                        <label class="flex justify-between cursor-pointer w-full relative space-x-4"
                               for="payment-method-<?= $escaper->escapeHtmlAttr($methodCodeAttr) ?>"
                        >
                            <div class="text-gray-700 font-bold flex flex-col">
                                <?= $escaper->escapeHtml($method->getTitle()) ?>

                                <?php if ($methodMetaData->hasSubTitle()): ?>
                                    <span class="text-gray-500 font-medium text-sm">
                                        <?= $escaper->escapeHtml($methodMetaData->getSubTitle()) ?>
                                    </span>
                                <?php endif ?>
                            </div>

                            <?php if ($methodMetaData->canRenderIcon()): ?>
                                <div class="-mt-2.5">
                                    <?= /* @noEscape */ $methodMetaData->renderIcon() ?>
                                </div>
                            <?php endif ?>
                        </label>
                    </div>
                    <?php if ($viewModel->canShowMethod($block, $method, $magewire->method)): ?>
                        <?php $html = $viewModel->getMethodBlock($block, $method)->toHtml() ?>

                        <?php if (!empty($html)): ?>
                            <div id="<?= 'payment-method-view-' . $escaper->escapeHtmlAttr($methodCodeAttr) ?>" class="w-full pl-8 mt-4">
                                <?= /* @noEscape */ $html ?>
                            </div>
                        <?php endif ?>
                    <?php endif ?>
                </li>
            <?php endforeach ?>
        </ol>
    <?php else: ?>
        <div class="message warning">
            <?= $escaper->escapeHtml(__('No Payment method available.')) ?>
        </div>
    <?php endif ?>
</div>
