<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */

?>
<script>
function adyenPaymentMethodRegisterEvent() {
    const method = this.$el.dataset.method;

    window.addEventListener('checkout:step:loaded', () => {
        if(method && document.getElementById('payment-method-list')) {
            window.dispatchEvent(new CustomEvent('checkout:payment:method-activate', { detail: { method: method} }))
        }
    }, { once: true })

    return {}
}
window.addEventListener('alpine:init', () => Alpine.data('adyenPaymentMethodRegisterEvent', adyenPaymentMethodRegisterEvent), {once: true});
</script>
<?php $hyvaCsp->registerInlineScript() ?>