<?php

use Adyen\Hyva\Magewire\Payment\Method\AbstractPaymentMethodWire;
use Magento\Framework\Escaper;

/** @var AbstractPaymentMethodWire $magewire  */
/** @var Escaper $escaper */

?>

<div
        x-data="adyenDefaultComponent"
        data-container-name="<?= $magewire->getContainerName() ?>"
        data-method-code="<?= $magewire->getMethodCode() ?>">
    <div id="<?= $escaper->escapeHtml($magewire->getContainerName()) ?>ActionContainer" wire:ignore></div>
</div>