<?php
use Adyen\Hyva\Magewire\Payment\Method\AbstractPaymentMethodWire;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var AbstractPaymentMethodWire $magewire  */
/** @var Template $block */
/** @var Escaper $escaper */

/**
 * @deprecated This file will be removed on V2. Use `adyen-facilypay-method.phtml` instead.
 */
?>

<div>

    <div id="<?= $escaper->escapeHtml($magewire->getContainerName()) ?>ActionContainer" wire:ignore></div>

    <div x-data="adyenPaymentMethodRendererAdyenFacilypay3xMethod"
         data-container-name="<?= $escaper->escapeHtmlAttr($magewire->getContainerName()) ?>"
         data-method-code="<?= $escaper->escapeHtmlAttr($magewire->getMethodCode()) ?>"
    ></div>
</div>
