<?php

/** @var Paypal $magewire */
/** @var Template $block */
/** @var Escaper $escaper */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Adyen\Hyva\Magewire\Payment\Method\Paypal;

?>

<div>
    <div id="PaypalActionContainer" wire:ignore></div>

    <script>
        class paypalComponentHandler extends componentHandler {
            buildConfiguration (paymentMethod, paymentMethodsExtraInfo) {
                let baseComponentConfiguration = super.buildConfiguration(paymentMethod, paymentMethodsExtraInfo);
                let paypalConfiguration = Object.assign(baseComponentConfiguration, paymentMethodsExtraInfo[paymentMethod.type].configuration);
                paypalConfiguration.showPayButton = true;

                return paypalConfiguration
            }
        }

        window.addEventListener('checkout:payment:method-activate', async (event) => {
            await init(event.detail.method);
        });

        window.addEventListener('adyen:payment_component:refresh', async (event) => {
            await init(event.detail.method);
        });

        async function init(methodCode) {
            try {
                let wire = Magewire.find('checkout.payment.method.' + methodCode);
                let paypalHandler = new paypalComponentHandler(
                    methodCode,
                    wire,
                    'PaypalActionContainer'
                );

                if (methodCode !== 'adyen_paypal') {
                    paypalHandler.renderMethodUnavailableMessage();
                    return;
                }

                if (wire.get('requiresShipping')) {
                    paypalHandler.renderMessage('Please select shipping method.');
                } else {
                    let rawResponse = wire.get('paymentResponse');
                    let paymentMethods = JSON.parse(rawResponse);
                    await paypalHandler.activateWalletMethod(methodCode, paymentMethods);
                    hidePrimaryButton();
                }
            } catch (e) {
            }
        }
    </script>
</div>
