<?php

/** @var CreditCard $magewire */

use Adyen\Hyva\Magewire\Payment\Method\CreditCard;

?>

<div
        x-data="adyenCcComponent"
        data-method="<?= $magewire->getConfiguration()->getValue('adyenCc/title') ?>"
        data-enable-store-details="<?= $magewire->getConfiguration()->isCCEnableStoreDetails($magewire->userIsGuest()) ?>"
        data-has-holder-name="<?= $magewire->getConfiguration()->getValue('adyen/hasHolderName') ?>"
        data-holder-name-required="<?= $magewire->getConfiguration()->getValue('adyen/holderNameRequired') ?>"
        data-installments="<?= $magewire->getFormattedInstallments() ?>"
>
    <div id="CreditCardActionContainer" wire:ignore class="w-full max-w-md"></div>
</div>