<?php

/** @var Klarna $magewire */
/** @var Template $block */
/** @var Escaper $escaper */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Adyen\Hyva\Magewire\Payment\Method\Klarna;

?>

<div>
    <div id="KlarnaActionContainer" wire:ignore></div>

    <script>
        class klarnaComponentHandler extends componentHandler {
            buildConfiguration (paymentMethod, paymentMethodsExtraInfo) {
                let baseComponentConfiguration = super.buildConfiguration(paymentMethod, paymentMethodsExtraInfo);
                return Object.assign(baseComponentConfiguration, paymentMethodsExtraInfo[paymentMethod.type].configuration)
            }
        }

        window.addEventListener('checkout:payment:method-list-boot', async (event) => {
            unmountAdyenComponent();
            await init(event.detail.method);
        });

        window.addEventListener('checkout:payment:method-activate', async (event) => {
            await init(event.detail.method);
        });

        async function init(methodCode) {
            try {
                let wire = Magewire.find('checkout.payment.method.' + methodCode);
                wire.refreshProperties()
                    .then(() => {
                        let klarnaHandler = new klarnaComponentHandler(
                            methodCode,
                            wire,
                            'KlarnaActionContainer'
                        );

                        window.AdyenPaymentHandler = klarnaHandler;

                        if (methodCode !== 'adyen_klarna') {
                            klarnaHandler.renderMethodUnavailableMessage();
                            return;
                        }

                        if (wire.get('requiresShipping')) {
                            klarnaHandler.renderMessage('Please select shipping method.');
                        } else {
                            let rawResponse = wire.get('paymentResponse');
                            let paymentMethods = JSON.parse(rawResponse);
                            klarnaHandler.activatePaymentMethod(methodCode, paymentMethods, 'KlarnaActionContainer');
                            showPrimaryButton();
                        }
                }).catch(() => {
                    console.log('Error occurred during Klarna component load')
                });
            } catch (e) {
            }
        }
    </script>
</div>
