<?php

/** @var CreditCard $magewire */
/** @var Template $block */
/** @var Escaper $escaper */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Adyen\Hyva\Magewire\Payment\Method\CreditCard;

?>

<div>
    <div id="CreditCardActionContainer" wire:ignore class="w-full max-w-md"></div>

    <script>
        window.addEventListener('checkout:payment:method-activate', async () => {
            let creditCardHandler = await init();

            if (creditCardHandler) {
                await activateCc(creditCardHandler);
                window.dispatchEvent(new CustomEvent('cc-method-active', {detail: {method: '<?= $magewire->getMethodCode() ?>'}}));
            }
        });

        async function init() {
            try {
                let wire = Magewire.find('checkout.payment.method.adyen_cc');
                let creditCardHandler = new componentHandler(
                    '<?= $escaper->escapeJs($magewire->getMethodCode()) ?>',
                    wire,
                    'CreditCardActionContainer'
                );

                return creditCardHandler;
            } catch (e) {
                return null;
            }
        }

        async function activateCc(creditCardHandler) {
            let creditCardConfiguration = {
                enableStoreDetails: '<?= $escaper->escapeJs($magewire->getConfiguration()->isCCEnableStoreDetails($magewire->userIsGuest()))?>',
                brands: <?= $magewire->getBrands() ?>,
                hasHolderName: '<?= $escaper->escapeJs($magewire->getConfiguration()->getValue('adyen/hasHolderName')) ?>',
                holderNameRequired: '<?= $escaper->escapeJs($magewire->getConfiguration()->getValue('adyen/holderNameRequired')) ?>',
                paymentMethodsResponse: <?= /* @noEscape */ $magewire->getPaymentResponse() ?>.paymentMethodsResponse,
                onChange: function(state, component) {
                    if (!state.isValid) {
                        hyvaCheckout.navigation.disableButtonPlaceOrder();
                    } else {
                        creditCardHandler.clearMessage();
                        hyvaCheckout.navigation.enableButtonPlaceOrder();
                    }
                },
                installmentOptions: <?= /* @noEscape */ $magewire->getFormattedInstallments() ?>,
                showInstallmentAmounts: true,
                onBrand: function(state) {
                    creditCardHandler.setCreditCardType(creditCardHandler.getCcCodeByAltCode(state.brand));
                },
                name: "Credit Card",
                type: "card",
                code: '<?= $escaper->escapeJs($magewire->getMethodCode()) ?>'
            };

            let paymentMethodsExtraInfo = <?= /* @noEscape */ $magewire->getPaymentResponse() ?>.paymentMethodsExtraDetails;

            let configuration = creditCardHandler.buildConfiguration(creditCardConfiguration, paymentMethodsExtraInfo);

            let component = await creditCardHandler.buildComponent(
                <?= /* @noEscape */ $magewire->getPaymentResponse() ?>.paymentMethodsResponse
            );

            creditCardHandler.mountComponent(component, creditCardConfiguration.type, configuration);

            hyvaCheckout.payment.activate('<?= $escaper->escapeJs($magewire->getMethodCode()) ?>',
                {
                    async placeOrder() {
                        let stateData = creditCardHandler.getActionComponent().data;
                        creditCardHandler.placeOrder(stateData);
                    },
                    placeOrderViaJs() {
                        return true
                    }
                },
                document.getElementById('CreditCardActionContainer')
            );
        }
    </script>
</div>
