<?php

use Adyen\Hyva\Magewire\Payment\Method\AbstractPaymentMethodWire;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var AbstractPaymentMethodWire $magewire  */
/** @var Template $block */
/** @var Escaper $escaper */

?>

<div>
    <div id="<?= $magewire->getContainerName() ?>ActionContainer" wire:ignore></div>

    <script>
        window.addEventListener('checkout:payment:method-list-boot', async (event) => {
            unmountAdyenComponent();
            await init(event.detail.method);
        });

        window.addEventListener('checkout:payment:method-activate', async (event) => {
            await init(event.detail.method);
        });

        async function init(methodCode) {
            try {
                let wire = Magewire.find('checkout.payment.methods.' + methodCode);

                wire.refreshProperties()
                    .then(() => {
                        let methodHandler = new componentHandler(
                            methodCode,
                            wire,
                            '<?= $magewire->getContainerName() ?>ActionContainer'
                        );

                        window.AdyenPaymentHandler = methodHandler;

                        if (methodCode !== '<?= $magewire->getMethodCode() ?>') {
                            methodHandler.renderMethodUnavailableMessage();
                            return;
                        }

                        if (wire.get('requiresShipping')) {
                            methodHandler.renderMessage('Please select shipping method.');
                        } else {
                            let rawResponse = wire.get('paymentResponse');
                            let paymentMethods = JSON.parse(rawResponse);
                            methodHandler.activatePaymentMethod(methodCode, paymentMethods, '<?= $magewire->getContainerName() ?>ActionContainer');
                            showPrimaryButton();
                        }
                }).catch(() => {
                    console.log(`Error occurred during ${methodCode} component load`)
                });
            } catch (e) {
            }
        }
    </script>
</div>
