<?php

/** @var AbstractPaymentMethodWire $magewire */
/** @var Template $block */
/** @var Escaper $escaper */

use Adyen\Hyva\Magewire\Payment\Method\AbstractPaymentMethodWire;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

?>

<div>
    <div id="<?= $escaper->escapeHtml($magewire->getContainerName()) ?>ActionContainer" wire:ignore></div>

    <div x-data="adyenPaymentMethodRendererAdyenAmazonpayMethod"
         data-container-name="<?= $escaper->escapeHtmlAttr($magewire->getContainerName()) ?>"
    ></div>
</div>
