<?php

use Adyen\Hyva\Magewire\Payment\Method\AbstractPaymentMethodWire;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var AbstractPaymentMethodWire $magewire  */
/** @var Template $block */
/** @var Escaper $escaper */

?>

<div>
    <div id="<?= $escaper->escapeHtml($magewire->getContainerName()) ?>ActionContainer" wire:ignore></div>

    <div x-data="adyenPaymentMethodRendererAdyenDefaultMethod"
         data-container-name="<?= $escaper->escapeHtmlAttr($magewire->getContainerName()) ?>"
         data-method-code="<?= $escaper->escapeHtmlAttr($magewire->getMethodCode()) ?>"
    ></div>
</div>
