<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */

/** Generated with hyva-csp-helper.php */
?>
<script>
    function adyenPaymentMethodRendererAdyenPaypalMethod() {
        class paypalComponentHandler extends componentHandler {
            buildConfiguration(paymentMethod, paymentMethodsExtraInfo) {
                let baseComponentConfiguration = super.buildConfiguration(paymentMethod, paymentMethodsExtraInfo);
                baseComponentConfiguration.showPayButton = true;

                return baseComponentConfiguration;
            }
        }

        window.addEventListener('checkout:payment:method-list-boot', async (event) => {
            unmountAdyenComponent();
            await init(event.detail.method);
        });

        window.addEventListener('checkout:payment:method-activate', async (event) => {
            await init(event.detail.method);
        });

        async function init(methodCode) {
            try {
                let wire = Magewire.find('checkout.payment.methods.' + methodCode);
                wire.refreshProperties()
                    .then(() => {
                        let paypalHandler = new paypalComponentHandler(
                            methodCode,
                            wire,
                            'PaypalActionContainer'
                        );

                        window.AdyenPaymentHandler = paypalHandler;

                        if (methodCode !== 'adyen_paypal') {
                            paypalHandler.renderMethodUnavailableMessage();
                            return;
                        }

                        if (wire.get('requiresShipping')) {
                            paypalHandler.renderMessage("<?= $escaper->escapeJs(__('Please select shipping method.')) ?>");
                        } else {
                            let rawResponse = wire.get('paymentResponse');
                            let paymentMethods = JSON.parse(rawResponse);
                            paypalHandler.activatePaymentMethod(methodCode, paymentMethods);
                            hidePrimaryButton();
                        }
                    }).catch(() => {
                        console.log('Error occurred during Paypal component load')
                    });
            } catch (e) {
            }
        }

        return {}
    }

    window.addEventListener('alpine:init', () => Alpine.data('adyenPaymentMethodRendererAdyenPaypalMethod', adyenPaymentMethodRendererAdyenPaypalMethod), {once: true});
</script>
<?php $hyvaCsp->registerInlineScript() ?>
