<?php

/** @var AbstractPaymentMethodWire $magewire */
/** @var Template $block */
/** @var Escaper $escaper */

use Adyen\Hyva\Magewire\Payment\Method\AbstractPaymentMethodWire;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

?>

<div>
    <div id="GooglePayActionContainer" wire:ignore></div>

    <div x-data="adyenPaymentMethodRendererAdyenGooglepayMethod"></div>
</div>
